version: "3.1"

services:
    xmas:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/home/node
            - /home/node/node_modules
        working_dir: /home/node
