version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.1.1
jobs:
  build:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run: npm install
      - aws-cli/setup:
          profile_name: default
      - run: aws --version
      - run: aws s3 ls
      - run: npm run deploy